site_name: Notes Of Professional-JavaScript-for-Web-Developers
nav:
    - 'Chapter1-What_Is_JavaScript.md'
    - 'Chapter2-JavaScript_in_HTML.md'
    - 'Chapter3-Language_Basics.md'
    - 'Chapter4-Variables_Scope_And_Memory.md'
    - 'Chapter5-Basic_Reference_Types.md'
    - 'Chapter6-Collection_Reference_Types.md'
    - 'Chapter7-Iterators_and_Generators.md'
    - 'Chapter8-Objects_Classes_and_Object-Oriented_Programming.md'
    - 'Chapter9-Proxies_and_Reflect.md'
    - 'Chapter10-Functions.md'
    - 'Chapter11-Promises_and_Async_Functions.md'
    - 'Chapter12-The_Browser_Object_Model.md'
    - 'Chapter13-Client_Detection.md'
    - 'Chapter14-The_Document_Object_Model.md'
    - 'Chapter15-DOM_Extensions.md'
    - 'Chapter16-DOM_Levels_2_and_3.md'
    - 'Chapter17-Events.md'
    - 'Chapter18-Animation_and_Graphics_with_Canvas.md'
    - 'Chapter19-Sctipting_Forms.md'
    - 'Chapter20-JavaScript_APIs.md'
    - 'Chapter21-Error_Handling_and_Debugging.md'
    - 'Chapter22-XML_in_JavaScript.md'
    - 'Chapter23-JSON.md'
    - 'Chapter24-Network_Requests_and_Remote_Resources.md'
    - 'Chapter25-Client-Side_Storage.md'
    - 'Chapter26-Modules.md'
    - 'Chapter27-Workers.md'
    - 'Chapter28-Best_Practices.md'
theme: readthedocs